#55 feat: 사용 가능한 힌트 개수를 초과했을 때 스낵바 띄우도록 구현
Next-Room/NextRoom-Android pull request #56
Opened 2024-02-19 15:51 UTC by juhwankim-dev

<img src="https://github.com/Next-Room/NextRoom-Android/assets/76620764/19f94df9-c904-4fe4-9bae-f6a1f9782629" width=300 />

- 사용 가능한 힌트 개수 체크하는 로직이 없어서 추가했습니다
- GameViewModel에서 InputState.Error 로 힌트 개수 초과 에러 방출해서 사용하려고 했는데
스낵바가 중복으로 뜨더라고.
보니까 GameScreenState에 시간초를 저장하는 변수가 있는데 이게 바뀌면서
GameFragment의 render를 1초마다 호출하고 있어
그래서 inputState가 같은 값이어도 중복으로 또 처리되더라
그래서 effect로 처리했습니당
- 스낵바라는 형태와 메시지는 내가 임의로 정함. 나중에 디자이너랑 합의해서 개선하는 쪽으로 갈게

2024-02-19 16:03 UTC, mangbaam requested changes

2024-02-19 16:03 UTC, mangbaam commented on presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameViewModel.kt
> +        if (state.usedHintsCount < state.totalHintCount) {
이미 오픈했던 힌트는 카운트 증가 없이 또 조회할 수 있기 때문에 조건문을 개선해야 할 듯 합니다.
totalHintCount 가 3이었을 때 3개의 힌트를 오픈했다면, 이미 오픈했던 힌트는 다시 조회할 수 없을 것 같네요!

2024-02-19 16:03 UTC, mangbaam commented on presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameViewModel.kt
> +                // TODO: 현재는 사용하는 곳이 없어 문제가 없지만, state가 중복으로 수집되어 사용될 수 있음. 수정 필요
이 주석은 무슨 의미일까?

2024-02-19 16:46 UTC, juhwankim-dev commented on presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameViewModel.kt
> +        if (state.usedHintsCount < state.totalHintCount) {
앗 맞네! 사용했던 힌트 조건문도 추가해두었습니당

2024-02-19 16:52 UTC, mangbaam approved these changes

2024-02-19 16:52 UTC, mangbaam commented on presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameViewModel.kt
> +                emitOpenHintEffect(hint)
[의견]

이 두개 조건은 통합해도 될 것 같아!
state.usedHints 가 Set 이라서 두 조건의 로직이 완전히 동일해질거야

2024-02-23 11:46 UTC, juhwankim-dev commented on presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameViewModel.kt
> +                // TODO: 현재는 사용하는 곳이 없어 문제가 없지만, state가 중복으로 수집되어 사용될 수 있음. 수정 필요
GameScreenState안에 second랑 inputState 2개가 있다고 했을때
(1, error) -> (2, error) -> (3, error) ...
fragment 쪽에서는 초가 바뀔때마다 state를 계속 collect 하잖아
그러면 저 에러를 화면에 중복해서 보여줄 수 있다는 뜻이였어

초 세는걸 따로 state로 빼거나
에러 보여주는걸 event로 따로 빼거나
수정이 필요할 것 같다는 뜻이였습니당

2024-02-23 11:52 UTC, juhwankim-dev commented on presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameViewModel.kt
> +                emitOpenHintEffect(hint)
맞넹! 수정 완료했습니다!

2024-02-27 04:24 UTC, mangbaam commented on presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameViewModel.kt
> +                // TODO: 현재는 사용하는 곳이 없어 문제가 없지만, state가 중복으로 수집되어 사용될 수 있음. 수정 필요
초를 따로 빼는 건 좋은 거 같아! 나중에 내가 작업할게!

2024-02-27 15:57 UTC, juhwankim-dev commented on presentation/src/main/java/com/nextroom/nextroom/presentation/ui/main/GameViewModel.kt
> +                // TODO: 현재는 사용하는 곳이 없어 문제가 없지만, state가 중복으로 수집되어 사용될 수 있음. 수정 필요
문제 없으면 Resolve 부탁해용~

2024-02-27 17:06 UTC, merged